### PR TITLE
Comment by William on sat

### PR DESCRIPTION
**Pull request by wnbittle**
avatar: 

@GoldSpark What doesn't work?

### CODE REVIEW

**Comment by goldspark** [comment]
Yea it was me messing up ONE line of code and for 2 hours straight I was like wtf. I didnt normalize axis.... Sorry it is working perfectly now thank you.

**Comment by wnbittle** [comment]
We've all been there.  Would love it if you could provide some detail on what fixed your issue to help others.

**Comment by goldspark** [comment]
Well for penetration resolution I needed to project vertices of any shape on an normalized axis which I did not do. After normalizing the axis and projecting vertices it fixed the problem.

**Comment by wnbittle** [comment]
@goldspark Thanks for the feedback - I wasn't clear, sorry about that, but meant if you could post another comment on the site with the detail you mentioned, that would help others.  I can do it as well, just let me know.

**Pull request merged**
